[project]
name = "rwm"
version = "2.0.1"

[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[tool.rooster]
changelog_ignore_labels = ["internal", "ci", "dependencies"]
version_files = [
    "pyproject.toml",
    "Cargo.toml",
]